"""Fail-closed release-evaluation attestation for live model inference.

The evaluation record is intentionally not generated by the training pipeline.  It
is a separate, reviewer-authored release artifact that must describe an evaluation
performed on data outside model fitting and calibration.
"""

from __future__ import annotations

import json
import math
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime
from hashlib import sha256
from pathlib import Path
from typing import Any

RELEASE_EVALUATION_FILENAME = "release_evaluation.json"
RELEASE_CHECKSUM_FILENAME = "release_evaluation.json.sha256"
RELEASE_SCHEMA_VERSION = 1
_SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")
_MAX_METADATA_BYTES = 4 * 1024 * 1024


class ReleaseEvaluationError(ValueError):
    """Raised when a release evaluation cannot authorize live inference."""


def _sha256_file(path: Path) -> str:
    digest = sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _require_local_file(root: Path, filename: str) -> Path:
    path = root / filename
    if not path.is_file():
        raise ReleaseEvaluationError(f"{filename} is required in the artifact directory")
    if path.is_symlink():
        raise ReleaseEvaluationError(f"{filename} must be a regular local file, not a symlink")
    if path.stat().st_size > _MAX_METADATA_BYTES:
        raise ReleaseEvaluationError(f"{filename} exceeds the metadata size limit")
    return path


def _object_without_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ReleaseEvaluationError(f"duplicate JSON key is not allowed: {key}")
        result[key] = value
    return result


def _reject_nonfinite_json(value: str) -> None:
    raise ReleaseEvaluationError(f"non-finite JSON value is not allowed: {value}")


def _load_json_object(path: Path) -> dict[str, Any]:
    try:
        text = path.read_text(encoding="utf-8")
        value = json.loads(
            text,
            object_pairs_hook=_object_without_duplicate_keys,
            parse_constant=_reject_nonfinite_json,
        )
    except ReleaseEvaluationError:
        raise
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ReleaseEvaluationError(f"{path.name} is not valid UTF-8 JSON") from exc
    if not isinstance(value, dict):
        raise ReleaseEvaluationError(f"{path.name} must contain a JSON object")
    return value


def _require_sha256(value: Any, field: str) -> str:
    if not isinstance(value, str) or not _SHA256_PATTERN.fullmatch(value):
        raise ReleaseEvaluationError(f"{field} must be a lowercase SHA-256 digest")
    return value


def _require_nonempty_text(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ReleaseEvaluationError(f"{field} must be a non-empty string")
    return value.strip()


def _require_review_time(value: Any) -> str:
    reviewed_at = _require_nonempty_text(value, "reviewed_at")
    try:
        parsed = datetime.fromisoformat(reviewed_at.replace("Z", "+00:00"))
    except ValueError as exc:
        raise ReleaseEvaluationError("reviewed_at must be an ISO-8601 timestamp") from exc
    if parsed.utcoffset() is None:
        raise ReleaseEvaluationError("reviewed_at must include a timezone offset")
    return reviewed_at


def _read_detached_checksum(checksum_path: Path) -> str:
    try:
        checksum_text = checksum_path.read_text(encoding="ascii").strip()
    except (OSError, UnicodeError) as exc:
        raise ReleaseEvaluationError(
            f"{RELEASE_CHECKSUM_FILENAME} must be readable ASCII text"
        ) from exc
    match = re.fullmatch(
        rf"([0-9a-f]{{64}})(?:[ \t]+\*?{re.escape(RELEASE_EVALUATION_FILENAME)})?",
        checksum_text,
    )
    if match is None:
        raise ReleaseEvaluationError(
            f"{RELEASE_CHECKSUM_FILENAME} must contain one lowercase SHA-256 digest"
        )
    return match.group(1)


def _validated_metrics(value: Any, *, drug: str) -> Mapping[str, int | float]:
    if not isinstance(value, dict) or not value:
        raise ReleaseEvaluationError(f"{drug}: metrics must be a non-empty object")
    validated: dict[str, int | float] = {}
    for raw_name, raw_value in value.items():
        name = _require_nonempty_text(raw_name, f"{drug}: metric name")
        if isinstance(raw_value, bool) or not isinstance(raw_value, (int, float)):
            raise ReleaseEvaluationError(f"{drug}: metric {name!r} must be numeric")
        if not math.isfinite(float(raw_value)):
            raise ReleaseEvaluationError(f"{drug}: metric {name!r} must be finite")
        validated[name] = raw_value
    required_counts = ("n_samples", "n_resistant", "n_susceptible", "n_groups")
    for name in required_counts:
        metric = validated.get(name)
        if isinstance(metric, bool) or not isinstance(metric, int) or metric <= 0:
            raise ReleaseEvaluationError(f"{drug}: metric {name!r} must be a positive integer")
    if validated["n_resistant"] + validated["n_susceptible"] != validated["n_samples"]:
        raise ReleaseEvaluationError(f"{drug}: class support must sum to n_samples")
    for name in ("coverage", "called_accuracy", "false_susceptible_rate"):
        metric = validated.get(name)
        if not isinstance(metric, (int, float)) or isinstance(metric, bool):
            raise ReleaseEvaluationError(f"{drug}: metric {name!r} is required")
        if not 0.0 <= float(metric) <= 1.0:
            raise ReleaseEvaluationError(f"{drug}: metric {name!r} must lie in [0, 1]")
    if float(validated["coverage"]) <= 0.0:
        raise ReleaseEvaluationError(f"{drug}: measured call coverage must be positive")
    return validated


def _manifest_supported_pairs(
    manifest: Mapping[str, Any], *, species: str, requested_drugs: Sequence[str]
) -> set[tuple[str, str]]:
    models = manifest.get("models")
    if not isinstance(models, list):
        raise ReleaseEvaluationError("manifest.json models must be a list")
    requested = {drug.casefold() for drug in requested_drugs}
    supported: set[tuple[str, str]] = set()
    seen_manifest_pairs: set[tuple[str, str]] = set()
    for entry in models:
        if not isinstance(entry, dict):
            raise ReleaseEvaluationError("manifest.json contains an invalid model entry")
        entry_species = entry.get("species")
        entry_drug = entry.get("drug")
        if not isinstance(entry_species, str) or not entry_species.strip():
            raise ReleaseEvaluationError("manifest model species must be non-empty")
        if not isinstance(entry_drug, str) or not entry_drug.strip():
            raise ReleaseEvaluationError("manifest model drug must be non-empty")
        pair = (entry_species.casefold(), entry_drug.casefold())
        if pair in seen_manifest_pairs:
            raise ReleaseEvaluationError("manifest.json contains duplicate species/drug models")
        seen_manifest_pairs.add(pair)
        if pair[0] == species.casefold() and pair[1] in requested:
            supported.add(pair)
    return supported


def _validated_drug_evaluations(value: Any) -> dict[tuple[str, str], Mapping[str, Any]]:
    if not isinstance(value, list):
        raise ReleaseEvaluationError("drug_evaluations must be a list")
    result: dict[tuple[str, str], Mapping[str, Any]] = {}
    for entry in value:
        if not isinstance(entry, dict):
            raise ReleaseEvaluationError("drug_evaluations contains an invalid entry")
        species = _require_nonempty_text(entry.get("species"), "drug evaluation species")
        drug = _require_nonempty_text(entry.get("drug"), "drug evaluation drug")
        pair = (species.casefold(), drug.casefold())
        if pair in result:
            raise ReleaseEvaluationError(f"duplicate drug evaluation: {species}/{drug}")
        if entry.get("supported") is not True:
            raise ReleaseEvaluationError(f"{species}/{drug}: supported must be exactly true")
        if entry.get("policy_constraints_satisfied") is not True:
            raise ReleaseEvaluationError(
                f"{species}/{drug}: policy_constraints_satisfied must be exactly true"
            )
        _validated_metrics(entry.get("metrics"), drug=f"{species}/{drug}")
        result[pair] = entry
    return result


@dataclass(frozen=True, slots=True)
class ReleaseEvaluation:
    """Validated static release attestation, pending/including live version match."""

    artifact_dir: Path
    release_sha256: str
    manifest_sha256: str
    dataset_sha256: str
    split_sha256: str
    reviewer: str
    reviewed_at: str
    annotation_feature_schema_version: str
    annotation_tool_version: str
    annotation_database_version: str
    evaluated_pairs: frozenset[tuple[str, str]]

    def verify_files_unchanged(self) -> None:
        """Recheck gate bindings immediately before live model execution."""

        release_path = self.artifact_dir / RELEASE_EVALUATION_FILENAME
        manifest_path = self.artifact_dir / "manifest.json"
        try:
            current_release = _sha256_file(release_path)
            current_manifest = _sha256_file(manifest_path)
        except OSError as exc:
            raise ReleaseEvaluationError(
                "release or manifest file changed during analysis"
            ) from exc
        if current_release != self.release_sha256:
            raise ReleaseEvaluationError("release_evaluation.json changed during analysis")
        if current_manifest != self.manifest_sha256:
            raise ReleaseEvaluationError("manifest.json changed after release validation")

    def verify_annotation(
        self,
        *,
        feature_schema_version: str,
        tool_version: str | None,
        database_version: str | None,
    ) -> None:
        """Require exact, case-sensitive live annotation provenance matches."""

        live_feature_schema = _require_nonempty_text(
            feature_schema_version, "live annotation feature schema version"
        )
        live_tool = _require_nonempty_text(tool_version, "live annotation tool version")
        live_database = _require_nonempty_text(database_version, "live annotation database version")
        if live_database.startswith("unverified:"):
            raise ReleaseEvaluationError("live annotation database version is unverified")
        expected_and_live = (
            (
                "feature schema",
                self.annotation_feature_schema_version,
                live_feature_schema,
            ),
            ("tool", self.annotation_tool_version, live_tool),
            ("database", self.annotation_database_version, live_database),
        )
        for label, expected, live in expected_and_live:
            if expected != live:
                raise ReleaseEvaluationError(
                    f"annotation {label} version mismatch: release={expected!r}, live={live!r}"
                )
        self.verify_files_unchanged()


def load_release_evaluation(
    artifact_dir: str | Path,
    *,
    species: str,
    requested_drugs: Sequence[str],
) -> ReleaseEvaluation:
    """Validate the signed-off release record and its registry-manifest binding.

    This performs only static validation.  Call :meth:`ReleaseEvaluation.verify_annotation`
    with live extractor provenance before invoking any model.
    """

    root = Path(artifact_dir).resolve()
    requested = tuple(str(drug).strip() for drug in requested_drugs)
    if not species.strip():
        raise ReleaseEvaluationError("species must be non-empty")
    if not requested or any(not drug for drug in requested):
        raise ReleaseEvaluationError("requested_drugs must contain non-empty names")
    if len({drug.casefold() for drug in requested}) != len(requested):
        raise ReleaseEvaluationError("requested_drugs must be unique")

    release_path = _require_local_file(root, RELEASE_EVALUATION_FILENAME)
    checksum_path = _require_local_file(root, RELEASE_CHECKSUM_FILENAME)
    manifest_path = _require_local_file(root, "manifest.json")

    release_sha256 = _sha256_file(release_path)
    if _read_detached_checksum(checksum_path) != release_sha256:
        raise ReleaseEvaluationError("release_evaluation.json detached checksum mismatch")

    payload = _load_json_object(release_path)
    schema_version = payload.get("schema_version")
    if (
        isinstance(schema_version, bool)
        or not isinstance(schema_version, int)
        or schema_version != RELEASE_SCHEMA_VERSION
    ):
        raise ReleaseEvaluationError("release evaluation schema_version must be exactly 1")
    if payload.get("release_eligible") is not True:
        raise ReleaseEvaluationError("release_eligible must be exactly true")
    if payload.get("group_disjoint_verified") is not True:
        raise ReleaseEvaluationError("group_disjoint_verified must be exactly true")
    if payload.get("target_workflow_validated") is not True:
        raise ReleaseEvaluationError("target_workflow_validated must be exactly true")

    dataset_sha256 = _require_sha256(payload.get("dataset_sha256"), "dataset_sha256")
    split_sha256 = _require_sha256(payload.get("split_sha256"), "split_sha256")
    reviewer = _require_nonempty_text(payload.get("reviewer"), "reviewer")
    reviewed_at = _require_review_time(payload.get("reviewed_at"))

    manifest_sha256 = _sha256_file(manifest_path)
    expected_manifest_sha256 = _require_sha256(payload.get("manifest_sha256"), "manifest_sha256")
    if expected_manifest_sha256 != manifest_sha256:
        raise ReleaseEvaluationError("release evaluation does not match manifest.json SHA-256")

    annotation = payload.get("annotation")
    if not isinstance(annotation, dict):
        raise ReleaseEvaluationError("annotation must be an object with exact pinned versions")
    annotation_feature_schema_version = _require_nonempty_text(
        annotation.get("feature_schema_version"), "annotation.feature_schema_version"
    )
    annotation_tool_version = _require_nonempty_text(
        annotation.get("tool_version"), "annotation.tool_version"
    )
    annotation_database_version = _require_nonempty_text(
        annotation.get("database_version"), "annotation.database_version"
    )
    if annotation_database_version.casefold().startswith("unverified:"):
        raise ReleaseEvaluationError("annotation.database_version must be verified")

    manifest = _load_json_object(manifest_path)
    supported_pairs = _manifest_supported_pairs(
        manifest,
        species=species,
        requested_drugs=requested,
    )
    evaluations = _validated_drug_evaluations(payload.get("drug_evaluations"))
    missing_evaluations = sorted(supported_pairs - evaluations.keys())
    if missing_evaluations:
        labels = ", ".join(f"{pair[0]}/{pair[1]}" for pair in missing_evaluations)
        raise ReleaseEvaluationError(
            f"requested supported drugs lack positive evaluation records: {labels}"
        )

    return ReleaseEvaluation(
        artifact_dir=root,
        release_sha256=release_sha256,
        manifest_sha256=manifest_sha256,
        dataset_sha256=dataset_sha256,
        split_sha256=split_sha256,
        reviewer=reviewer,
        reviewed_at=reviewed_at,
        annotation_feature_schema_version=annotation_feature_schema_version,
        annotation_tool_version=annotation_tool_version,
        annotation_database_version=annotation_database_version,
        evaluated_pairs=frozenset(supported_pairs),
    )


__all__ = [
    "RELEASE_CHECKSUM_FILENAME",
    "RELEASE_EVALUATION_FILENAME",
    "RELEASE_SCHEMA_VERSION",
    "ReleaseEvaluation",
    "ReleaseEvaluationError",
    "load_release_evaluation",
]
